### ISSUE TITLE
hola estas ahi 

### ISSUE THREAD

**Issue by CamiloATP** [TrabajoGrupo/Solemne_3#1]
axel si estas vivo necesito que le pongas css a lo que voy a subir ahora deja tu numero de celu aqui @acsel21

**Comment by CamiloATP** [comment]
lo acabo de subir le falta el css agregaselo, voy a terminar el registrar atencion y me tiro con lo de selenium @acsel21

**Comment by acsel21** [comment]
camilo, estoy agregando el CSSal formulario...se me habia olvidado lo del selenium jajaja

**Comment by acsel21** [comment]
camilo estas ???
