### ISSUE TITLE
Agregale css 

### ISSUE THREAD

**Issue by CamiloATP** [TrabajoGrupo/Solemne_3#2]

**Comment by acsel21** [comment]
Hay que agregar el CSS al formulario ?????

**Comment by CamiloATP** [comment]
si

**Comment by CamiloATP** [comment]
ahora voy a subir el que hace el registro en 5 min más

**Comment by CamiloATP** [comment]
pegate los trucos con el css voy a tratar de hacer alguna validación de selenium.. @acsel21

**Comment by CamiloATP** [comment]
Ya lo subi ponele css nomas

**Comment by CamiloATP** [comment]
El que subi ahora si xDD, ese edita con css @acsel21
