### ISSUE TITLE
camilo te funciono el selenium ?? me genera un conflicto no me deja instalar el jar del server, por que pasa eso ? @CamiloATP

### ISSUE THREAD

**Issue by acsel21** [TrabajoGrupo/Solemne_3#3]

**Comment by CamiloATP** [comment]
Noooooo, cache como funcionaba bien xD lo descarge el pluggin en mozilla podia grabar pero no corre la prueba xd, creo que hice solo lo de validar el rut xDD 

PD: ya se lo envie

**Comment by CamiloATP** [comment]
xd en resume no lo hice funcionar xD

**Comment by acsel21** [comment]
jajajajaja selenium qlo... la aplicacion te funciono bien ?? @CamiloATP
